In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
loans = pd.read_csv("lending_club_new_data.csv")
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_late_fee  \
0  27.65            0               1         3  ...                0.00   
1   1.00            0               5         3  ...                0.00   
2   8.72            0               2         2  ...                0.00   
3  20.00            0               1        10  ...               16.97   
4  11.20            0               3         9  ...                0.00   

   recoveries  collection_recovery_fee  last_pymnt_amnt  bad_loans  \
0        0.00                     0.00           171.62          0   
1      117.08                     1.11           119.66          1   
2        0.00                     0.00           649.91          0   
3        0.00                     0.00           357.48          0   
4        0.00                     0.00           161.03          0   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 24 columns]

In [3]:
loans['good_loans'] = loans['bad_loans'].apply(lambda y: 'yes' if y==0 else 'no')

In [4]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]

In [5]:
X = loans.drop(['bad_loans','good_loans'], axis=1)
y = loans['good_loans']

In [6]:
X.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  total_rec_int  \
0  27.65            0               1         3  ...         861.07   
1   1.00            0               5         3  ...         435.17   
2   8.72            0               2         2  ...         603.65   
3  20.00            0               1        10  ...        2209.33   
4  11.20            0               3         9  ...         631.38   

   total_rec_late_fee  recoveries  collection_recovery_fee  last_pymnt_amnt  \
0                0.00        0.00                     0.00           171.62   
1                0.00      117.08                     1.11           119.66   
2                0.00        0.00                     0.00           649.91   
3               16.97        0.00                     0.00           357.48   
4                0.00        0.00                     0.00           161.03   

   emp_length_num  grade_num  sub_grade_num  delinq_2yrs_zero  \
0              11          5            0.4                 1   
1               1          4            0.8                 1   
2              11          4            1.0                 1   
3              11          4            0.2                 1   
4               4          6            0.8                 1   

   payment_inc_ratio  
0            8.14350  
1            2.39320  
2            8.25955  
3            8.27585  
4            5.21533  

[5 rows x 23 columns]

In [7]:
print(X.shape, y.shape)

(9516, 23) (9516,)


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=124)

In [10]:
print(X_train.shape, X_test.shape)

(6661, 23) (2855, 23)


In [11]:
print(y_train.shape, y_test.shape)

(6661,) (2855,)


In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model2 = DecisionTreeClassifier()

In [14]:
model2.fit(X_train, y_train)

DecisionTreeClassifier()

In [15]:
prediction2 = model2.predict(X_test)

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

In [17]:
print(confusion_matrix(y_test, prediction2))

[[ 443   12]
 [   9 2391]]


In [18]:
print(classification_report(y_test, prediction2))

              precision    recall  f1-score   support

          no       0.98      0.97      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.98      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
rf_model2 = RandomForestClassifier(n_estimators = 150)  # Case sensitive functions

In [21]:
rf_model2.fit(X_train, y_train)

RandomForestClassifier(n_estimators=150)

In [22]:
rf_prediction = model2.predict(X_test)

In [23]:
print(confusion_matrix(y_test, rf_prediction))

[[ 443   12]
 [   9 2391]]


In [25]:
print(confusion_matrix(y_test, prediction2))

[[ 443   12]
 [   9 2391]]


In [27]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

          no       0.98      0.97      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.98      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [28]:
print(classification_report(y_test, prediction2))

              precision    recall  f1-score   support

          no       0.98      0.97      0.98       455
         yes       1.00      1.00      1.00      2400

    accuracy                           0.99      2855
   macro avg       0.99      0.98      0.99      2855
weighted avg       0.99      0.99      0.99      2855



In [29]:
loans.head()

loan_amnt  funded_amnt  funded_amnt_inv  int_rate  installment  annual_inc  \
0       5000         5000             4975     10.65       162.87       24000   
1       2500         2500             2500     15.27        59.83       30000   
2       2400         2400             2400     15.96        84.33       12252   
3      10000        10000            10000     13.49       339.31       49200   
4       5000         5000             5000      7.90       156.46       36000   

     dti  delinq_2yrs  inq_last_6mths  open_acc  ...  recoveries  \
0  27.65            0               1         3  ...        0.00   
1   1.00            0               5         3  ...      117.08   
2   8.72            0               2         2  ...        0.00   
3  20.00            0               1        10  ...        0.00   
4  11.20            0               3         9  ...        0.00   

   collection_recovery_fee  last_pymnt_amnt  bad_loans  emp_length_num  \
0                     0.00           171.62          0              11   
1                     1.11           119.66          1               1   
2                     0.00           649.91          0              11   
3                     0.00           357.48          0              11   
4                     0.00           161.03          0               4   

   grade_num  sub_grade_num  delinq_2yrs_zero  payment_inc_ratio  good_loans  
0          5            0.4                 1            8.14350         yes  
1          4            0.8                 1            2.39320          no  
2          4            1.0                 1            8.25955         yes  
3          4            0.2                 1            8.27585         yes  
4          6            0.8                 1            5.21533         yes  

[5 rows x 25 columns]